app_key: "tgyx1nv271dadey"
app_secret: <%= ENV["APP_SECRET"] %>
access_token: "0ciggksifiqv53tc"
access_token_secret: <%= ENV["ACCESS_TOKEN_SECRET"] %>
user_id: "416307168"
access_type: "app_folder"